### ISSUE TITLE
红黑树问题

### ISSUE THREAD

**Issue by wuzhengdong1** [zanwen/algorithm#1]
你好，很高兴看到您的分享，我想问一下在红黑树的插入中，绿色框中的俩个红色节点在一起应该怎么处理

**Comment by zanwen** [comment]
你说的是添加节点添加到等效B树叶子节点中的红色节点的情况吧：
![](https://user-gold-cdn.xitu.io/2019/12/4/16eceffcfcfc7067?imageView2/0/w/1280/h/960/format/webp/ignore-error/1)
以上述的被添加节点及其红色父节点组成的LL情况为例（为了方便处理添加逻辑，我们总是先将被添加节点染红再添加）
因为添加该节点后，等效B树节点将包含4个红黑树节点，因此需要发生类似B树中**上溢**的操作，即选取中间的一个节点向上层移动，该节点两侧节点独立成两个B数节点。而这个向上层移动的节点我们又可以将其染红作为被添加节点，复用整个红黑树添加节点之后的修复逻辑进行递归调用处理。

**Comment by wuzhengdong1** [comment]
嗯嗯，知道了，谢谢！------------------ 原始邮件 ------------------
发件人: "Anwen"<notifications@github.com>
发送时间: 2019年12月15日(星期天) 中午1:38
收件人: "zanwen/algorithm"<algorithm@noreply.github.com>;
抄送: "Bob"<1126790951@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zanwen/algorithm] 红黑树问题 (#1)



你说的是添加节点添加到等效B树叶子节点中的红色节点的情况吧：
 
 以上述的被添加节点及其红色父节点组成的LL情况为例（为了方便处理添加逻辑，我们总是先将被添加节点染红再添加）
 因为添加该节点后，等效B树节点将包含4个红黑树节点，因此需要发生类似B树中上溢的操作，即选取中间的一个节点向上层移动，该节点两侧节点独立成两个B数节点。而这个向上层移动的节点我们又可以将其染红作为被添加节点，复用整个红黑树添加节点之后的修复逻辑进行递归调用处理。
 
&mdash;

**Comment by wuzhengdong1** [comment]
谢谢 已经知道了 感谢分享
